CREATE TABLE geocode (
    id serial primary key,
    beneficiary_id TEXT,
    query_country_code VARCHAR(2),
    query_country VARCHAR(20),
    query_type VARCHAR(20),
    query_state VARCHAR(100),
    query_region VARCHAR(100),
    query_county VARCHAR(100),
    query_city VARCHAR(100),
    query_postal_code VARCHAR(100),
    query_address VARCHAR(200),
    result_country VARCHAR(50),
    result_region VARCHAR(100),
    result_county VARCHAR(100),
    result_city VARCHAR(100),
    result_postal_code VARCHAR(100),
    result_street VARCHAR(100),
    result_number VARCHAR(100),
    result_full_address VARCHAR(255),
    result_lat NUMERIC,
    result_long NUMERIC,
    geocoded BOOLEAN DEFAULT FALSE,
    lau VARCHAR(50)
);